---
title: "Project"
author: "seymacakir"
date: "05 06 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# install the required packages first
require(jsonlite)
require(httr)
require(data.table)
library(lubridate)
library(data.table)
library(dplyr)
library(ggplot2)
library(knitr)
library(tidyr)
library(tidyverse)
library(scales)
library(ggcorrplot)
library(forecast)
library(urca)
library(zoo)
library(reshape)
library(GGally)
library(PerformanceAnalytics)


get_token <- function(username, password, url_site){
  
  post_body = list(username=username,password=password)
  post_url_string = paste0(url_site,'/token/')
  result = POST(post_url_string, body = post_body)
  
  # error handling (wrong credentials)
  if(result$status_code==400){
    print('Check your credentials')
    return(0)
  }
  else if (result$status_code==201){
    output = content(result)
    token = output$key
  }
  
  return(token)
}

get_data <- function(start_date='2020-03-20', token, url_site){
  
  post_body = list(start_date=start_date,username=username,password=password)
  post_url_string = paste0(url_site,'/dataset/')
  
  header = add_headers(c(Authorization=paste('Token',token,sep=' ')))
  result = GET(post_url_string, header, body = post_body)
  output = content(result)
  data = data.table::rbindlist(output)
  data[,event_date:=as.Date(event_date)]
  data = data[order(product_content_id,event_date)]
  return(data)
}


send_submission <- function(predictions, token, url_site, submit_now=F){
  
  format_check=check_format(predictions)
  if(!format_check){
    return(FALSE)
  }
  
  post_string="list("
  for(i in 1:nrow(predictions)){
    post_string=sprintf("%s'%s'=%s",post_string,predictions$product_content_id[i],predictions$forecast[i])
    if(i<nrow(predictions)){
      post_string=sprintf("%s,",post_string)
    } else {
      post_string=sprintf("%s)",post_string)
    }
  }
  
  submission = eval(parse(text=post_string))
  json_body = jsonlite::toJSON(submission, auto_unbox = TRUE)
  submission=list(submission=json_body)
  
  print(submission)
  # {"31515569":2.4,"32737302":2.4,"32939029":2.4,"4066298":2.4,"48740784":2.4,"6676673":2.4, "7061886":2.4, "73318567":2.4, "85004":2.4} 
  
  if(!submit_now){
    print("You did not submit.")
    return(FALSE)      
  }
  
  
  header = add_headers(c(Authorization=paste('Token',token,sep=' ')))
  post_url_string = paste0(url_site,'/submission/')
  result = POST(post_url_string, header, body=submission)
  
  if (result$status_code==201){
    print("Successfully submitted. Below you can see the details of your submission")
  } else {
    print("Could not submit. Please check the error message below, contact the assistant if needed.")
  }
  
  print(content(result))
  
}

check_format <- function(predictions){
  
  if(is.data.frame(predictions) | is.data.frame(predictions)){
    if(all(c('product_content_id','forecast') %in% names(predictions))){
      if(is.numeric(predictions$forecast)){
        print("Format OK")
        return(TRUE)
      } else {
        print("forecast information is not numeric")
        return(FALSE)                
      }
    } else {
      print("Wrong column names. Please provide 'product_content_id' and 'forecast' columns")
      return(FALSE)
    }
    
  } else {
    print("Wrong format. Please provide data.frame or data.table object")
    return(FALSE)
  }
  
}

# this part is main code
subm_url = 'http://46.101.163.177'

u_name = "Group3"
p_word = "LaQjwxkIGSGhBrRj"
submit_now = TRUE

username = u_name
password = p_word

token = get_token(username=u_name, password=p_word, url=subm_url)
data = get_data(token=token,url=subm_url)

predictions=unique(data[,list(product_content_id)])
predictions[,forecast:=2.3]

#send_submission(predictions, token, url=subm_url, submit_now=T)

```



```{r}

# join  data 
rawdata <- read.csv("C:/Users/seyma/OneDrive/Belgeler/GitHub/spring21-seymacakir/files/project/ProjectRawData.csv", header = TRUE,sep = ",")
rawdata <- as.data.table(rawdata)
colnames <- c( "price","event_date","product_content_id","sold_count" , "visit_count" , "favored_count" , "basket_count","category_sold",     "category_brand_sold", "category_visits"  ,   "ty_visits"  ,  "category_basket",    "category_favored" )
rawdata <- rawdata[,..colnames]
rawdata <- rawdata[!is.na(sold_count)]
rawdata$event_date <- as.Date(rawdata$event_date, format = "%Y-%m-%d")
#rawdata$product_content_id <- as.factor(rawdata$product_content_id)
#data$product_content_id <- as.factor(data$product_content_id)



rawdata <- rbind(rawdata,data) %>% distinct(event_date, product_content_id, .keep_all = TRUE ) %>% arrange(event_date) %>% as.data.table()
 

forecastdata <- tail(rawdata,9) 
forecastdata[, event_date := as.Date(tail(rawdata,9)$event_date + 1)]

rawdata <- rbind(rawdata,forecastdata) %>% distinct(event_date, product_content_id, .keep_all = TRUE ) %>% arrange(event_date) %>% as.data.table()

 # add  month and weekday  component data 

rawdata[,w_day:= wday(event_date)]
rawdata[,mon:= month(event_date)]


# campaign 

rawdata[, is_campaign := 0]
rawdata[rawdata$event_date >= as.Date("2021-05-07") & rawdata$event_date <= as.Date("2021-05-09"), is_campaign := 1]
rawdata[rawdata$event_date >= as.Date("2020-06-18") & rawdata$event_date <= as.Date("2020-06-20") , is_campaign := 1]
rawdata[rawdata$event_date >= as.Date("2021-06-18") & rawdata$event_date <= as.Date("2021-06-20") , is_campaign := 1]
rawdata[rawdata$event_date >= as.Date("2020-09-08") & rawdata$event_date <= as.Date("2020-09-12") , is_campaign := 1]
rawdata[rawdata$event_date >= as.Date("2021-09-10") & rawdata$event_date <= as.Date("2021-09-12") , is_campaign := 1]
rawdata[rawdata$event_date >= as.Date("2020-11-09") & rawdata$event_date <= as.Date("2020-11-11") , is_campaign := 1]
rawdata[rawdata$event_date >= as.Date("2020-11-25") & rawdata$event_date <= as.Date("2020-11-29") , is_campaign := 1]
rawdata[rawdata$event_date >= as.Date("2021-03-09") & rawdata$event_date <= as.Date("2021-03-12") , is_campaign := 1]
rawdata[rawdata$event_date >= as.Date("2021-04-27") & rawdata$event_date <= as.Date("2021-04-29") , is_campaign := 1]
rawdata[rawdata$event_date >= as.Date("2021-06-09") & rawdata$event_date <= as.Date("2021-06-10") , is_campaign := 1]
rawdata[rawdata$event_date >= as.Date("2020-12-21") & rawdata$event_date <= as.Date("2020-12-24") , is_campaign := 1]





# create data table for each product

product_id <- unique(rawdata$product_content_id)
products <- list()
for ( i in 1:length(product_id)){
products[[i]] <- as.data.table(rawdata[product_content_id == product_content_id[i]])
}


```

```{r graphs }



for(i in 9:9){
 
  
g1 <-ggplot(products[[i]], aes( x = event_date, y = sold_count)) + geom_line() + ggtitle(paste("product",i)) +theme_minimal()  
g2 <-ggplot(products[[i]], aes( y = sold_count, fill= factor(w_day))) + geom_boxplot() + 
  ggtitle(paste("product",i))+ theme_minimal() 
g3 <-ggplot(products[[i]], aes( y = sold_count, fill= factor(mon))) + geom_boxplot()+
      ggtitle(paste("product",i))+ theme_minimal() 
g4 <- ggplot(products[[i]], aes( x = sold_count)) + geom_histogram() + ggtitle(paste("product",i)) + theme_minimal()+
        facet_wrap(~factor(w_day))
g5 <-ggplot(products[[i]], aes( x = sold_count )) + geom_histogram() + theme_minimal()+ ggtitle(paste("product",i))+
      facet_wrap(~factor(mon))


print(g1)
print(g2)
print(g3)
print(g4)
print(g5)
ACF <- acf( products[[i]]$sold_count, plot = FALSE)
plot(ACF, main = paste("ACF OF Product",i))
PACF <- pacf( products[[i]]$sold_count, plot = FALSE)
plot(PACF, main = paste("PACF OF Product",i))

}
 





```

```{r}
accu=function(actual,forecast,model){
  model = model
  n=length(actual)
  error=actual-forecast
  mean=mean(actual)
  sd=sd(actual)
  CV=sd/mean
  FBias=sum(error)/sum(actual)
  MAPE=sum(abs(error/actual))/n
  RMSE=sqrt(sum(error^2)/n)
  MAD=sum(abs(error))/n
  MADP=sum(abs(error))/sum(abs(actual))
  WMAPE=MAD/mean
  l=data.frame(model,n,mean,sd,CV,FBias,MAPE,RMSE,MAD,MADP,WMAPE)
  return(l)
}
```


```{r}

product7 <- products[[7]]




product7[is.na(price)]$price <- mean(product7[!is.na(price)]$price)

product7[,trend := 1:.N]


acf(product7$sold_count)
pacf(product7$sold_count)

product7[ty_visits==1, ty_visits:= mean(ty_visits)]
product7 [, lag1:= shift(sold_count,1)]
product7[is.na(lag1), lag1 := 0]
product7 [, lag2:= shift(sold_count,2)]
product7[is.na(lag2), lag2 := mean(sold_count[1]) ]
product7 [, lag3:= shift(sold_count,3)]
product7[is.na(lag3), lag3 := mean(sold_count[1:2]) ]
product7 [, lag7:= shift(sold_count,7)]
product7[is.na(lag7), lag7 := mean(sold_count[1:6]) ]

product7 [, plag1:= shift(price,1)]
product7[is.na(plag1), plag1 := mean(price) ]


product7[, sqrt:= sqrt(sold_count)]
lambda <- BoxCox.lambda(product7$sold_count)
product7[, BoxCox := BoxCox(sold_count,lambda = lambda)]

test_dates <- tail(product7,15)$event_date
nextday <- tail(product7,1)
train7 <-  product7[!(event_date %in% test_dates)]
test_dates <- test_dates[1:14]
test7 <- product7[event_date %in% test_dates][1:14]

forecast_ahead <- 1


autoplot(ts(product7$sold_count))
lm7 <- lm( sold_count ~ price  + visit_count + basket_count + category_basket  + factor(mon) +  factor(is_campaign) + trend + lag1 + lag3 , train7)
summary(lm7)
checkresiduals(lm7)

plot(train7$sold_count, lm7$fitted)
ggplot() + geom_line(data = train7, aes(x = event_date, y = sold_count), color = "blue") + geom_line( aes( x = train7$event_date,y = lm7$fitted), color = "red")

autoplot(ts(product7$sqrt))
sqrt_lm7 <- lm(sqrt~  price  + visit_count  + basket_count + ty_visits  + factor(mon)  + lag1  + plag1 + factor(is_campaign) + category_visits + category_basket , train7 )
summary(sqrt_lm7)
checkresiduals(sqrt_lm7)

plot(train7$sold_count, (sqrt_lm7$fitted)^2)
ggplot() + geom_line(data = train7, aes(x = event_date, y = sold_count), color = "blue") + geom_line( aes( x = train7$event_date,y = (sqrt_lm7$fitted)^2), color = "red")



autoplot(ts(product7$BoxCox))
BoxCox_lm7 <- lm(BoxCox~ price + visit_count  + basket_count + category_sold + ty_visits  + factor(mon) + lag1 + lag7 + plag1 + factor(is_campaign)  + category_basket , train7)
summary(BoxCox_lm7)
checkresiduals(BoxCox_lm7)

plot(train7$sold_count, InvBoxCox(BoxCox_lm7$fitted, lambda = lambda))
ggplot() + geom_line(data = train7, aes(x = event_date, y = sold_count), color = "blue") +
  geom_line( aes( x = train7$event_date,y = InvBoxCox(BoxCox_lm7$fitted, lambda = lambda)), color = "red")

forecast_lm7=function(data,forecast_data){
    fitted_lm=lm(sold_count ~ price  + visit_count + basket_count + category_basket  + factor(mon) +  factor(is_campaign) + trend + lag1 + lag3 , data)
    forecasted=predict(fitted_lm,forecast_data)
    return(list(forecast=as.numeric(forecasted),model=fitted_lm))
}


forecast_lm7_sqrt=function(data,forecast_data){
    fitted_lm=lm(sqrt~   price  + visit_count  + basket_count + ty_visits  + factor(mon)  + lag1 + lag7  + plag1 + factor(is_campaign) + category_basket, data)
    forecasted=predict(fitted_lm,forecast_data)
    return(list(forecast=as.numeric(forecasted),model=fitted_lm))
}

forecast_BoxCox7=function(data,forecast_data){
    fitted_lm=lm(BoxCox~ price + visit_count  + basket_count + category_sold + ty_visits  + factor(mon) + lag1 + lag7 + plag1 + factor(is_campaign)  + category_basket , data)
    forecasted=  forecasted=predict(fitted_lm,forecast_data)
    return(list(forecast=as.numeric(forecasted),model=fitted_lm))
}



sqrt_forecasted_sold<- c()
BoxCox_forecasted_sold <- c()
lm_forecasted_sold <- c()

for(i in 1:length(test_dates)){
    current_date=test_dates[i]-forecast_ahead
    past_data=product7[event_date<=current_date]
    forecast_data=product7[event_date==test_dates[i]]
    
    forecasted=forecast_lm7_sqrt(past_data,forecast_data)
    sqrt_forecasted_sold[i]<- forecasted$forecast^2
    
    forecasted=forecast_BoxCox7(past_data,forecast_data)
    BoxCox_forecasted_sold[i]<- InvBoxCox(forecasted$forecast, lambda = lambda)
    
    forecasted=forecast_lm7(past_data,forecast_data)
    lm_forecasted_sold[i]<- forecasted$forecast
}



prediction7 <- data.table("event_date" = test_dates,lm_forecasted_sold,sqrt_forecasted_sold,BoxCox_forecasted_sold)
prediction7[, combine1 := (3*lm_forecasted_sold+2*sqrt_forecasted_sold)/5]

for(i in 2:length(prediction7)){
  
  print(accu(test7$sold_count,prediction7[,..i],colnames(prediction7[,..i])))
}



ggplot() + geom_line(data = product7[event_date %in% test_dates], aes(x= event_date, y = sold_count)) + 
  geom_line(data = prediction7,aes( x = event_date,y =sqrt_forecasted_sold, color = "Sqrt"))+ 
   geom_line(data = prediction7,aes( x = event_date,y =lm_forecasted_sold, color = "No Transformation")) + 
  geom_line(data = prediction7,aes( x = event_date,y =BoxCox_forecasted_sold, color = "BoxCox")) +
  geom_line(data = prediction7,aes( x = event_date,y =combine1, color = "Combine1"))
  
  





temp <- tail(product7[,c(1,5,6,7,8,9,10,11,12,13)],15)

test7[,c(1,5,6,7,8,9,10,11,12,13)] <- temp[1:14]





testsqrt_forecasted_sold<- c()
testBoxCox_forecasted_sold <- c()
testlm_forecasted_sold <- c()

for(i in 1:length(test_dates)){
    current_date=test_dates[i]-forecast_ahead
    past_data=product7[event_date<=current_date]
    forecast_data=test7[i]
    
    forecasted=forecast_lm7_sqrt(past_data,forecast_data)
    testsqrt_forecasted_sold[i]<- forecasted$forecast^2
    
    forecasted=forecast_BoxCox7(past_data,forecast_data)
    testBoxCox_forecasted_sold[i]<- InvBoxCox(forecasted$forecast, lambda = lambda)
    
    forecasted=forecast_lm7(past_data,forecast_data)
    testlm_forecasted_sold[i]<- forecasted$forecast
}


testprediction7 <- data.table("event_date" = test_dates,testlm_forecasted_sold,testsqrt_forecasted_sold,testBoxCox_forecasted_sold)
testprediction7[, combine1 := (21*testlm_forecasted_sold+15*testsqrt_forecasted_sold)/(21+15)]

for(i in 2:length(testprediction7)){
  
  print(accu(test7$sold_count,testprediction7[,..i],colnames(testprediction7[,..i])))
}


ggplot() + geom_line(data = product7[event_date %in% test_dates], aes(x= event_date, y = sold_count)) + 
  geom_line(data = testprediction7,aes( x = event_date,y =testsqrt_forecasted_sold, color = "Sqrt"))+ 
   geom_line(data = testprediction7,aes( x = event_date,y =testlm_forecasted_sold, color = "No Transformation")) + 
  geom_line(data = testprediction7,aes( x = event_date,y =testBoxCox_forecasted_sold, color = "BoxCox")) +
  geom_line(data = testprediction7,aes( x = event_date,y =combine1, color = "Combine1"))






```



```{r}



my_data <- product7[, 4:13]
chart.Correlation(my_data, pch=19)


xreg7 <- product7[ , c( "price","visit_count",  "basket_count","category_basket" , "ty_visits","is_campaign")]
xreg7 <- as.matrix(xreg7)

add_arima=function(data,h,f){
 ts <- ts(data$sold_count,frequency =f )
 add <- decompose(ts, type = "add") 
 fitted <- auto.arima(add$random, seasonal= FALSE)
 seasonal <- add$seasonal[(length(data$sold_count)-f): (length(data$sold_count)-f+h-1)]
 trend <- tail(add$trend[!is.na(add$trend)],1)
 forecastted <- as.numeric(forecast(fitted,h)$mean) + seasonal + trend
 return(forecastted)
}

xreg_add_arima=function(data,h,f, xreg){
 ts <- ts(data$sold_count,frequency =f )
 add <- decompose(ts, type = "add") 
 train_xreg<- xreg[1:length(data$event_date)]
 for_xreg <- xreg[(length(data$event_date))]
 fitted <- auto.arima(add$random, seasonal= FALSE, xreg = train_xreg)
 seasonal <- add$seasonal[(length(data$sold_count)-f): (length(data$sold_count)-f+h-1)]
 trend <- tail(add$trend[!is.na(add$trend)],1)
 forecastted <- as.numeric(forecast(fitted,h,xreg = for_xreg)$mean) + seasonal + trend
 return(forecastted)
}





mul_arima=function(data,h,f){
 
 ts <- ts(data$sold_count,frequency =f )
 mul <- decompose(ts, type = "mul") 
 fitted <- auto.arima(mul$random, seasonal= FALSE)
 seasonal <- mul$seasonal[(length(data$sold_count)-f): (length(data$sold_count)-f+h-1)]
 trend <- tail(mul$trend[!is.na(mul$trend)],1)
 forecasted <- as.numeric(forecast(fitted,h)$mean)*seasonal*trend
 return(forecasted)
}

xreg_mul_arima=function(data,h,f, xreg){
 ts <- ts(data$sold_count,frequency =f )
 mul <- decompose(ts, type = "mul") 
 train_xreg<- xreg[1:length(data$event_date)]
 for_xreg <- xreg[(length(data$event_date)) ]
 fitted <- auto.arima(mul$random, seasonal= FALSE, xreg = train_xreg)
 seasonal <- mul$seasonal[(length(data$sold_count)-f): (length(data$sold_count)-f+h-1)]
 trend <- tail(mul$trend[!is.na(mul$trend)],1)
 forecastted <- as.numeric(forecast(fitted,h,xreg = for_xreg)$mean)*seasonal*trend
 return(forecastted)
}


testprediction7[, add_arima_forecasted := 0]
testprediction7[ , mul_arima_forecasted := 0]
testprediction7[, reg_add_arima_forecasted := 0]
testprediction7[ ,reg_mul_arima_forecasted := 0]

for(i in 1:length(test_dates)){
    current_date=test_dates[i]-forecast_ahead
    past_data=product7[event_date<=current_date]
    forecast_data=product7[event_date==test_dates[i]]
    
    
    testprediction7$add_arima_forecasted[i] <- add_arima(past_data,1,7)
    testprediction7$reg_add_arima_forecasted[i] <- xreg_add_arima(past_data,1,7,xreg7)
    testprediction7$mul_arima_forecasted[i] <- mul_arima(past_data,1,7)
    testprediction7$reg_mul_arima_forecasted[i] <- xreg_mul_arima(past_data,1,7,xreg7)
}

testprediction7 [ ,combine2 := (3*testlm_forecasted_sold+5*testsqrt_forecasted_sold + 1*reg_mul_arima_forecasted)/9]


ggplot() + geom_line(data = product7[event_date %in% test_dates], aes(x= event_date, y = sold_count)) + 
  geom_line(data = testprediction7,aes( x = event_date,y = add_arima_forecasted, color = "add_arima_forecasted"))+ 
   geom_line(data = testprediction7,aes( x = event_date,y =mul_arima_forecasted, color = "mul_arima_forecasted")) +
   geom_line(data = testprediction7,aes( x = event_date,y = reg_add_arima_forecasted, color = "reg_add_arima_forecasted"))+ 
   geom_line(data = testprediction7,aes( x = event_date,y =reg_mul_arima_forecasted , color = "reg_mul_arima_forecasted"))+ 
  geom_line(data = testprediction7,aes( x = event_date,y =combine2 , color = "combine2"))
  

  
  

testprediction7[,actual:= product7[event_date %in% test_dates]$sold_count]



melted_result=melt(testprediction7,c('event_date','actual'))

error7 =  data.table()

for(i in 2:(length(testprediction7))){
  

  error7 <- rbind(error7, accu(test7$sold_count,testprediction7[,..i],colnames(testprediction7[,..i])))
}



## forcast nex day

xreg <- as.matrix( nextday[ , c( "price","visit_count",  "basket_count","category_basket" , "ty_visits","is_campaign")])



add_arima(product7,1,7)
mul_arima(product7,1,7)
xreg_mul_arima(product7,1,7, xreg7)
xreg_add_arima(product7,1,7, xreg7)
forecast_lm7(product7,nextday)$forecast
InvBoxCox(forecast_BoxCox7(product7,nextday)$forecast, lambda = lambda)
(forecast_lm7_sqrt(product7,nextday)$forecast)^2
 

( (21*forecast_lm7(product7,nextday)$forecast)  + (15*((forecast_lm7_sqrt(product7,nextday)$forecast)^2)) ) / (21+15)



```








```{r}

product8 <- products[[8]]




product8[is.na(price)]$price <- mean(product8[(!is.na(price)) & (price>= 0) ]$price)
product8[price<=0]$price <- mean(product8[!is.na(price)]$price)



summary(product8)


product8[,trend := 1:.N]

product8[ty_visits==1, ty_visits:= mean(ty_visits)]
product8 [, lag1:= shift(sold_count,1)]
product8[is.na(lag1), lag1 := 0]
product8 [, lag2:= shift(sold_count,2)]
product8[is.na(lag2), lag2 := mean(sold_count[1]) ]
product8 [, lag5:= shift(sold_count,5)]
product8[is.na(lag5), lag5 := mean(sold_count[1:4]) ]
product8 [, lag7:= shift(sold_count,7)]
product8[is.na(lag7), lag7 := mean(sold_count[1:6]) ]




product8[ , price_lag_4 := shift(price,4)]
product8[ , price_lag_5 := shift(price,5)]
product8[ , price_lag_6 := shift(price,6)]
product8[ , price_lag_7 := shift(price,7)]
product8[is.na(price_lag_4)]$price_lag_4 <-mean(product8[is.na(price_lag_4)]$price_lag_4)
product8[is.na(price_lag_5)]$price_lag_5 <-mean(product8[is.na(price_lag_5)]$price_lag_5)
product8[is.na(price_lag_6)]$price_lag_6 <-mean(product8[is.na(price_lag_6)]$price_lag_6)
product8[is.na(price_lag_7)]$price_lag_7 <-mean(product8[is.na(price_lag_7)]$price_lag_7)

product8[is.na(price_lag_4), price_lag_4:= mean(price) ]
product8[is.na(price_lag_5), price_lag_5:= mean(price) ]
product8[is.na(price_lag_6), price_lag_6:= mean(price) ]
product8[is.na(price_lag_7), price_lag_7:= mean(price) ]



product8[, sqrt:= sqrt(sold_count)]
lambda <- BoxCox.lambda(product8$sold_count)
product8[, BoxCox := BoxCox(sold_count,lambda = lambda)]

test_dates <- tail(product8,15)$event_date
nextday <- tail(product8,1)
train8 <-  product8[!(event_date %in% test_dates)]
test_dates <- test_dates[1:14]
test8 <- product8[event_date %in% test_dates][1:14]



forecast_ahead <- 1




autoplot(ts(product8$sold_count))
lm8 <- lm( sold_count ~ price +   visit_count + basket_count + category_favored  +  factor( w_day )  + factor(mon)  + lag1 + lag2  + price_lag_4, train8)
summary(lm8)
checkresiduals(lm8)

plot(train8$sold_count, lm8$fitted)
ggplot() + geom_line(data = train8, aes(x = event_date, y = sold_count), color = "blue") + geom_line( aes( x = train8$event_date,y = lm8$fitted), color = "red")

autoplot(ts(product8$sqrt))
sqrt_lm8 <- lm(sqrt ~ price + visit_count  + basket_count +  category_favored + factor(w_day) + factor(mon) + lag1, data = train8)
summary(sqrt_lm8)
checkresiduals(sqrt_lm8)

plot(train8$sold_count, (sqrt_lm8$fitted)^2)
ggplot() + geom_line(data = train8, aes(x = event_date, y = sold_count), color = "blue") + geom_line( aes( x = train8$event_date,y = (sqrt_lm8$fitted)^2), color = "red")



autoplot(ts(product8$BoxCox))
BoxCox_lm8 <- lm(BoxCox~ price + visit_count  +  basket_count  + category_favored + factor( w_day ) + factor(mon) + lag1,train8)
summary(BoxCox_lm8)
checkresiduals(BoxCox_lm8)

plot(train8$sold_count, InvBoxCox(BoxCox_lm8$fitted, lambda = lambda))
ggplot() + geom_line(data = train8, aes(x = event_date, y = sold_count), color = "blue") +
  geom_line( aes( x = train8$event_date,y = InvBoxCox(BoxCox_lm8$fitted, lambda = lambda)), color = "red")

forecast_lm8=function(data,forecast_data){
    fitted_lm=lm( sold_count ~ price +   visit_count + basket_count + category_favored  +  factor( w_day )  + factor(mon)  + lag1 + lag2  + price_lag_4,data)
    forecasted=predict(fitted_lm,forecast_data)
    return(list(forecast=as.numeric(forecasted),model=fitted_lm))
}


forecast_lm8_sqrt=function(data,forecast_data){
    fitted_lm=lm(sqrt ~ price + visit_count  + basket_count +  category_favored + factor(w_day) + factor(mon) + lag1,data)
    forecasted=predict(fitted_lm,forecast_data)
    return(list(forecast=as.numeric(forecasted),model=fitted_lm))
}

forecast_BoxCox8=function(data,forecast_data){
    fitted_lm=lm(BoxCox~ price + visit_count  +  basket_count  + category_favored + factor( w_day ) + factor(mon) + lag1, data)
    forecasted=  forecasted=predict(fitted_lm,forecast_data)
    return(list(forecast=as.numeric(forecasted),model=fitted_lm))
}




sqrt_forecasted_sold<- c()
BoxCox_forecasted_sold <- c()

lm_forecasted_sold <- c()

for(i in 1:length(test_dates)){
  
    current_date=test_dates[i]-forecast_ahead
    past_data=product8[event_date<=current_date]
    forecast_data=product8[event_date==test_dates[i]]
    
    forecasted=forecast_lm8_sqrt(past_data,forecast_data)
    sqrt_forecasted_sold[i]<- (forecasted$forecast)^2
    
    
    forecasted=forecast_lm8(past_data,forecast_data)
    lm_forecasted_sold[i]<- forecasted$forecast
    
    forecasted=forecast_BoxCox8(past_data,forecast_data)
    BoxCox_forecasted_sold[i]<- InvBoxCox(forecasted$forecast, lambda = lambda)
}



prediction8 <- data.table("event_date" = test_dates,lm_forecasted_sold,sqrt_forecasted_sold,BoxCox_forecasted_sold)
#prediction8[, combine1 := (3*lm_forecasted_sold+2*sqrt_forecasted_sold)/5]

for(i in 2:length(prediction8)){
  
  print(accu(test8$sold_count,prediction8[,..i],colnames(prediction8[,..i])))
}



ggplot() + geom_line(data = product8[event_date %in% test_dates], aes(x= event_date, y = sold_count)) + 
  geom_line(data = prediction8,aes( x = event_date,y =sqrt_forecasted_sold, color = "Sqrt"))+ 
   geom_line(data = prediction8,aes( x = event_date,y =lm_forecasted_sold, color = "No Transformation")) + 
  geom_line(data = prediction8,aes( x = event_date,y =BoxCox_forecasted_sold, color = "BoxCox")) 
  #geom_line(data = prediction8,aes( x = event_date,y =combine1, color = "Combine1"))
  
  





temp <- tail(product8[,c(1,5,6,7,8,9,10,11,12,13)],15)

test8[,c(1,5,6,7,8,9,10,11,12,13)] <- temp[1:14]





testsqrt_forecasted_sold<- c()
testBoxCox_forecasted_sold <- c()
testlm_forecasted_sold <- c()

for(i in 1:length(test_dates)){
    current_date=test_dates[i]-forecast_ahead
    past_data=product8[event_date<=current_date]
    forecast_data=test8[i]
    
    forecasted=forecast_lm8(past_data,forecast_data)
    testlm_forecasted_sold[i]<-  round(forecasted$forecast,0)
    
    forecasted=forecast_lm8_sqrt(past_data,forecast_data)
    testsqrt_forecasted_sold[i]<- round(forecasted$forecast^2,0)
    
    forecasted=forecast_BoxCox8(past_data,forecast_data)
    if (InvBoxCox(forecasted$forecast, lambda = lambda) < 0 || InvBoxCox(forecasted$forecast, lambda = lambda) > (testsqrt_forecasted_sold[i] +testlm_forecasted_sold[i])){
      testBoxCox_forecasted_sold[i] <- (testsqrt_forecasted_sold[i] +testlm_forecasted_sold[i])/2
    }
    else {
    testBoxCox_forecasted_sold[i]<- round( InvBoxCox(forecasted$forecast, lambda = lambda),0)
    }
    
}


testprediction8 <- data.table("event_date" = test_dates,testlm_forecasted_sold,testsqrt_forecasted_sold,testBoxCox_forecasted_sold)

for(i in 2:length(testprediction8)){
  
  print(accu(test8$sold_count,testprediction8[,..i],colnames(testprediction8[,..i])))
}


ggplot() + geom_line(data = product8[event_date %in% test_dates], aes(x= event_date, y = sold_count)) + 
  geom_line(data = testprediction8,aes( x = event_date,y =testsqrt_forecasted_sold, color = "Sqrt"))+ 
   geom_line(data = testprediction8,aes( x = event_date,y =testlm_forecasted_sold, color = "No Transformation")) +   
    geom_line(data = testprediction8,aes( x = event_date,y =testBoxCox_forecasted_sold, color = "BoxCox")) 
 # geom_line(data = testprediction8,aes( x = event_date,y =combine1, color = "Combine1"))






```



```{r}



#my_data <- product8[, 4:13]
#chart.Correlation(my_data, pch=19)


xreg8 <- product8[ , c( "price","visit_count",  "basket_count","category_favored" )]
xreg8 <- as.matrix(xreg8)

add_arima=function(data,h,f){
 ts <- ts(data$sold_count,frequency =f )
 add <- decompose(ts, type = "add") 
 fitted <- auto.arima(add$random, seasonal= FALSE)
 seasonal <- add$seasonal[(length(data$sold_count)-f): (length(data$sold_count)-f+h-1)]
 trend <- tail(add$trend[!is.na(add$trend)],1)
 forecastted <- as.numeric(forecast(fitted,h)$mean) + seasonal + trend
 return(forecastted)
}

xreg_add_arima=function(data,h,f, xreg){
 ts <- ts(data$sold_count,frequency =f )
 add <- decompose(ts, type = "add") 
 train_xreg<- xreg[1:length(data$event_date)]
 for_xreg <- xreg[(length(data$event_date))]
 fitted <- auto.arima(add$random, seasonal= FALSE, xreg = train_xreg)
 seasonal <- add$seasonal[(length(data$sold_count)-f): (length(data$sold_count)-f+h-1)]
 trend <- tail(add$trend[!is.na(add$trend)],1)
 forecastted <- as.numeric(forecast(fitted,h,xreg = for_xreg)$mean) + seasonal + trend
 return(forecastted)
}





mul_arima=function(data,h,f){
 
 ts <- ts(data$sold_count,frequency =f )
 mul <- decompose(ts, type = "mul") 
 fitted <- auto.arima(mul$random, seasonal= FALSE)
 seasonal <- mul$seasonal[(length(data$sold_count)-f): (length(data$sold_count)-f+h-1)]
 trend <- tail(mul$trend[!is.na(mul$trend)],1)
 forecasted <- as.numeric(forecast(fitted,h)$mean)*seasonal*trend
 return(forecasted)
}

xreg_mul_arima=function(data,h,f, xreg){
 ts <- ts(data$sold_count,frequency =f )
 mul <- decompose(ts, type = "mul") 
 train_xreg<- xreg[1:length(data$event_date)]
 for_xreg <- xreg[(length(data$event_date)) ]
 fitted <- auto.arima(mul$random, seasonal= FALSE, xreg = train_xreg)
 seasonal <- mul$seasonal[(length(data$sold_count)-f): (length(data$sold_count)-f+h-1)]
 trend <- tail(mul$trend[!is.na(mul$trend)],1)
 forecastted <- as.numeric(forecast(fitted,h,xreg = for_xreg)$mean)*seasonal*trend
 return(forecastted)
}


testprediction8[, add_arima_forecasted := 0]
testprediction8[ , mul_arima_forecasted := 0]
testprediction8[, reg_add_arima_forecasted := 0]
testprediction8[ ,reg_mul_arima_forecasted := 0]

for(i in 1:length(test_dates)){
    current_date=test_dates[i]-forecast_ahead
    past_data=product8[event_date<=current_date]
    forecast_data=product8[event_date==test_dates[i]]
    
    
    testprediction8$add_arima_forecasted[i] <- round(add_arima(past_data,1,7),0)
    testprediction8$reg_add_arima_forecasted[i] <- round(xreg_add_arima(past_data,1,7,xreg8),0)
    testprediction8$mul_arima_forecasted[i] <- round( mul_arima(past_data,1,7),0)
    testprediction8$reg_mul_arima_forecasted[i] <- round( xreg_mul_arima(past_data,1,7,xreg8),0)
}

#testprediction8 [ ,combine2 := (3*testlm_forecasted_sold+5*testsqrt_forecasted_sold + 1*reg_mul_arima_forecasted)/9]


ggplot() + geom_line(data = product8[event_date %in% test_dates], aes(x= event_date, y = sold_count)) + 
  geom_line(data = testprediction8,aes( x = event_date,y = add_arima_forecasted, color = "add_arima_forecasted"))+ 
   geom_line(data = testprediction8,aes( x = event_date,y =mul_arima_forecasted, color = "mul_arima_forecasted")) +
   geom_line(data = testprediction8,aes( x = event_date,y = reg_add_arima_forecasted, color = "reg_add_arima_forecasted"))+ 
   geom_line(data = testprediction8,aes( x = event_date,y =reg_mul_arima_forecasted , color = "reg_mul_arima_forecasted"))
 # geom_line(data = testprediction8,aes( x = event_date,y =combine2 , color = "combine2"))
  

  
  

testprediction8[,actual:= product8[event_date %in% test_dates]$sold_count]



#melted_result=melt(testprediction8,c('event_date','actual'))

error8 =  data.table()

for(i in 2:(length(testprediction8))){
  

  error8 <- rbind(error8, accu(test8$sold_count,testprediction8[,..i],colnames(testprediction8[,..i])))
}



## forcast next day

xreg <- as.matrix( nextday[ , c( "price","visit_count",  "basket_count","category_favored")])



add_arima(product8,1,8)
mul_arima(product8,1,8)
xreg_mul_arima(product8,1,8, xreg8)
xreg_add_arima(product8,1,8, xreg8)
forecast_lm8(product8,nextday)$forecast
InvBoxCox(forecast_BoxCox8(product8,nextday)$forecast, lambda = lambda)
(forecast_lm8_sqrt(product8,nextday)$forecast)^2


```


```{r}



product9 <- products[[9]]


summary(product9)


product9[is.na(price)]$price <- mean(product9[(!is.na(price)) & (price>= 0) ]$price)
product9[price<=0]$price <- mean(product9[!is.na(price)]$price)



product9[,trend := 1:.N]

product9[ty_visits==1, ty_visits:= mean(ty_visits)]
product9 [, lag1:= shift(sold_count,1)]
product9[is.na(lag1), lag1 := 0]
product9 [, lag2:= shift(sold_count,2)]
product9[is.na(lag2), lag2 := mean(sold_count[1]) ]
product9 [, lag3:= shift(sold_count,3)]
product9[is.na(lag3), lag3 := mean(sold_count[1:2]) ]
product9 [, lag7:= shift(sold_count,7)]
product9[is.na(lag7), lag7 := mean(sold_count[1:6]) ]





product9[, sqrt:= sqrt(sold_count)]
lambda <- BoxCox.lambda(product9$sold_count)
product9[, BoxCox := BoxCox(sold_count,lambda = lambda)]

test_dates <- tail(product9,15)$event_date
nextday <- tail(product9,1)
train9 <-  product9[!(event_date %in% test_dates)]
test_dates <- test_dates[1:14]
test9 <- product9[event_date %in% test_dates][1:14]



forecast_ahead <- 1


autoplot(ts(product9$sold_count))
lm9 <- lm( sold_count ~ price  +  visit_count    +  basket_count  + favored_count + category_sold + category_visits + category_basket + category_favored + category_brand_sold  + factor(w_day)  + factor(mon) + trend  +   lag1 +  lag3   ,product9[4:.N] )
summary(lm9)
checkresiduals(lm9)



autoplot(ts(product9$sqrt))
sqrt_lm <- lm(sqrt~ price  +  visit_count    +  basket_count  + favored_count + category_sold + category_visits + category_basket + category_favored + category_brand_sold + ty_visits + factor(w_day)  + factor(mon)  +   lag1 +  lag3     , product9[4:.N] )
summary(sqrt_lm)
checkresiduals(sqrt_lm)


autoplot(ts(product9$BoxCox))
BoxCox_lm <- lm(BoxCox~price  +  visit_count    +  basket_count  + favored_count  + category_visits + category_basket  + ty_visits + factor(w_day)  + factor(mon)  +   lag1 +  lag3            
                , product9[4:.N] )
summary(BoxCox_lm)
checkresiduals(BoxCox_lm)


autoplot(ts(product9$sold_count))
lm9 <- lm( sold_count ~ price  +  visit_count    +  basket_count  + favored_count + category_sold + category_visits + category_basket + category_favored + category_brand_sold  + factor(w_day)  + factor(mon) + trend  +   lag1 +  lag3  + factor(is_campaign), train9)
summary(lm9)
checkresiduals(lm9)

plot(train9$sold_count, lm9$fitted)
ggplot() + geom_line(data = train9, aes(x = event_date, y = sold_count), color = "blue") + geom_line( aes( x = train9$event_date,y = lm9$fitted), color = "red")

autoplot(ts(product9$sqrt))
sqrt_lm9 <- lm(sqrt ~  price  +  visit_count    +  basket_count  + favored_count + category_sold + category_visits + category_basket + category_favored + category_brand_sold + ty_visits + factor(w_day)  + factor(mon)  +   lag1 +  lag3 + factor(is_campaign), data = train9)
summary(sqrt_lm9)
checkresiduals(sqrt_lm9)

plot(train9$sold_count, (sqrt_lm9$fitted)^2)
ggplot() + geom_line(data = train9, aes(x = event_date, y = sold_count), color = "blue") + geom_line( aes( x = train9$event_date,y = (sqrt_lm9$fitted)^2), color = "red")



autoplot(ts(product9$BoxCox))
BoxCox_lm9 <- lm(BoxCox~ price  +  visit_count    +  basket_count  + favored_count  + category_visits + category_basket  + ty_visits + factor(w_day)  + factor(mon)  + factor(is_campaign)+   lag1 +  lag3 ,train9)
summary(BoxCox_lm9)
checkresiduals(BoxCox_lm9)

plot(train9$sold_count, InvBoxCox(BoxCox_lm9$fitted, lambda = lambda))
ggplot() + geom_line(data = train9, aes(x = event_date, y = sold_count), color = "blue") +
  geom_line( aes( x = train9$event_date,y = InvBoxCox(BoxCox_lm9$fitted, lambda = lambda)), color = "red")

forecast_lm9=function(data,forecast_data){
    fitted_lm=lm( sold_count ~ price  + basket_count  + category_sold  + category_favored  + factor(w_day)  + factor(mon) + trend  +   lag1 +  lag3  + factor(is_campaign),data)
    forecasted=predict(fitted_lm,forecast_data)
    return(list(forecast=as.numeric(forecasted),model=fitted_lm))
}


forecast_lm9_sqrt=function(data,forecast_data){
    fitted_lm=lm(sqrt ~  price  +  basket_count  + category_sold  + category_favored + factor(w_day)  + factor(mon)  +   lag1 +  lag3 + factor(is_campaign),data)
    forecasted=predict(fitted_lm,forecast_data)
    return(list(forecast=as.numeric(forecasted),model=fitted_lm))
}

forecast_BoxCox9=function(data,forecast_data){
    fitted_lm=lm(BoxCox~ price    +  basket_count  + category_sold  + category_favored   + ty_visits + factor(w_day)  + factor(mon)  + factor(is_campaign)+   lag1 +  lag3, data)
    forecasted=  forecasted=predict(fitted_lm,forecast_data)
    return(list(forecast=as.numeric(forecasted),model=fitted_lm))
}




sqrt_forecasted_sold<- c()
BoxCox_forecasted_sold <- c()

lm_forecasted_sold <- c()

for(i in 1:length(test_dates)){
  
    current_date=test_dates[i]-forecast_ahead
    past_data=product9[event_date<=current_date]
    forecast_data=product9[event_date==test_dates[i]]
    
    forecasted=forecast_lm9_sqrt(past_data,forecast_data)
    sqrt_forecasted_sold[i]<- (forecasted$forecast)^2
    
    
    forecasted=forecast_lm9(past_data,forecast_data)
    lm_forecasted_sold[i]<- forecasted$forecast
    
    forecasted=forecast_BoxCox9(past_data,forecast_data)
    BoxCox_forecasted_sold[i]<- InvBoxCox(forecasted$forecast, lambda = lambda)
}



prediction9 <- data.table("event_date" = test_dates,lm_forecasted_sold,sqrt_forecasted_sold,BoxCox_forecasted_sold)
#prediction9[, combine1 := (3*lm_forecasted_sold+2*sqrt_forecasted_sold)/5]

for(i in 2:length(prediction9)){
  
  print(accu(test9$sold_count,prediction9[,..i],colnames(prediction9[,..i])))
}



ggplot() + geom_line(data = product9[event_date %in% test_dates], aes(x= event_date, y = sold_count)) + 
  geom_line(data = prediction9,aes( x = event_date,y =sqrt_forecasted_sold, color = "Sqrt"))+ 
   geom_line(data = prediction9,aes( x = event_date,y =lm_forecasted_sold, color = "No Transformation")) + 
  geom_line(data = prediction9,aes( x = event_date,y =BoxCox_forecasted_sold, color = "BoxCox")) 
  #geom_line(data = prediction9,aes( x = event_date,y =combine1, color = "Combine1"))
  
  





temp <- tail(product9[,c(1,5,6,7,8,9,10,11,12,13)],15)

test9[,c(1,5,6,7,8,9,10,11,12,13)] <- temp[1:14]





testsqrt_forecasted_sold<- c()
testBoxCox_forecasted_sold <- c()
testlm_forecasted_sold <- c()

for(i in 1:length(test_dates)){
    current_date=test_dates[i]-forecast_ahead
    past_data=product9[event_date<=current_date]
    forecast_data=test9[i]
    
    forecasted=forecast_lm9_sqrt(past_data,forecast_data)
    testsqrt_forecasted_sold[i]<- forecasted$forecast^2
    
    forecasted=forecast_BoxCox9(past_data,forecast_data)
    testBoxCox_forecasted_sold[i]<- InvBoxCox(forecasted$forecast, lambda = lambda)
    
    forecasted=forecast_lm9(past_data,forecast_data)
    testlm_forecasted_sold[i]<- forecasted$forecast
}


testprediction9 <- data.table("event_date" = test_dates,testlm_forecasted_sold,testsqrt_forecasted_sold,testBoxCox_forecasted_sold)

for(i in 2:length(testprediction9)){
  
  print(accu(test9$sold_count,testprediction9[,..i],colnames(testprediction9[,..i])))
}


ggplot() + geom_line(data = product9[event_date %in% test_dates], aes(x= event_date, y = sold_count)) + 
  geom_line(data = testprediction9,aes( x = event_date,y =testsqrt_forecasted_sold, color = "Sqrt"))+ 
   geom_line(data = testprediction9,aes( x = event_date,y =testlm_forecasted_sold, color = "No Transformation")) + 
  geom_line(data = testprediction9,aes( x = event_date,y =testBoxCox_forecasted_sold, color = "BoxCox")) 
 # geom_line(data = testprediction9,aes( x = event_date,y =combine1, color = "Combine1"))




xreg9 <- product9[ , c( "price","category_sold",  "basket_count","category_favored" )]
xreg9 <- as.matrix(xreg9)

add_arima=function(data,h,f){
 ts <- ts(data$sold_count,frequency =f )
 add <- decompose(ts, type = "add") 
 fitted <- auto.arima(add$random, seasonal= FALSE)
 seasonal <- add$seasonal[(length(data$sold_count)-f): (length(data$sold_count)-f+h-1)]
 trend <- tail(add$trend[!is.na(add$trend)],1)
 forecastted <- as.numeric(forecast(fitted,h)$mean) + seasonal + trend
 return(forecastted)
}

xreg_add_arima=function(data,h,f, xreg){
 ts <- ts(data$sold_count,frequency =f )
 add <- decompose(ts, type = "add") 
 train_xreg<- xreg[1:length(data$event_date)]
 for_xreg <- xreg[(length(data$event_date))]
 fitted <- auto.arima(add$random, seasonal= FALSE, xreg = train_xreg)
 seasonal <- add$seasonal[(length(data$sold_count)-f): (length(data$sold_count)-f+h-1)]
 trend <- tail(add$trend[!is.na(add$trend)],1)
 forecastted <- as.numeric(forecast(fitted,h,xreg = for_xreg)$mean) + seasonal + trend
 return(forecastted)
}





mul_arima=function(data,h,f){
 
 ts <- ts(data$sold_count,frequency =f )
 mul <- decompose(ts, type = "mul") 
 fitted <- auto.arima(mul$random, seasonal= FALSE)
 seasonal <- mul$seasonal[(length(data$sold_count)-f): (length(data$sold_count)-f+h-1)]
 trend <- tail(mul$trend[!is.na(mul$trend)],1)
 forecasted <- as.numeric(forecast(fitted,h)$mean)*seasonal*trend
 return(forecasted)
}

xreg_mul_arima=function(data,h,f, xreg){
 ts <- ts(data$sold_count,frequency =f )
 mul <- decompose(ts, type = "mul") 
 train_xreg<- xreg[1:length(data$event_date)]
 for_xreg <- xreg[(length(data$event_date)) ]
 fitted <- auto.arima(mul$random, seasonal= FALSE, xreg = train_xreg)
 seasonal <- mul$seasonal[(length(data$sold_count)-f): (length(data$sold_count)-f+h-1)]
 trend <- tail(mul$trend[!is.na(mul$trend)],1)
 forecastted <- as.numeric(forecast(fitted,h,xreg = for_xreg)$mean)*seasonal*trend
 return(forecastted)
}


testprediction9[, add_arima_forecasted := 0]
testprediction9[ , mul_arima_forecasted := 0]
testprediction9[, reg_add_arima_forecasted := 0]
testprediction9[ ,reg_mul_arima_forecasted := 0]

for(i in 1:length(test_dates)){
    current_date=test_dates[i]-forecast_ahead
    past_data=product9[event_date<=current_date]
    forecast_data=product9[event_date==test_dates[i]]
    
    
    testprediction9$add_arima_forecasted[i] <- add_arima(past_data,1,7)
    testprediction9$reg_add_arima_forecasted[i] <- xreg_add_arima(past_data,1,7,xreg9)
    testprediction9$mul_arima_forecasted[i] <- mul_arima(past_data,1,7)
    testprediction9$reg_mul_arima_forecasted[i] <- xreg_mul_arima(past_data,1,7,xreg9)
}

#testprediction9 [ ,combine2 := (3*testlm_forecasted_sold+5*testsqrt_forecasted_sold + 1*reg_mul_arima_forecasted)/9]


ggplot() + geom_line(data = product9[event_date %in% test_dates], aes(x= event_date, y = sold_count)) + 
  geom_line(data = testprediction9,aes( x = event_date,y = add_arima_forecasted, color = "add_arima_forecasted"))+ 
   geom_line(data = testprediction9,aes( x = event_date,y =mul_arima_forecasted, color = "mul_arima_forecasted")) +
   geom_line(data = testprediction9,aes( x = event_date,y = reg_add_arima_forecasted, color = "reg_add_arima_forecasted"))+ 
   geom_line(data = testprediction9,aes( x = event_date,y =reg_mul_arima_forecasted , color = "reg_mul_arima_forecasted"))
 # geom_line(data = testprediction9,aes( x = event_date,y =combine2 , color = "combine2"))
  

  
  

testprediction9[,actual:= product9[event_date %in% test_dates]$sold_count]



#melted_result=melt(testprediction9,c('event_date','actual'))

error9 =  data.table()

for(i in 2:(length(testprediction9))){
  

  error9 <- rbind(error9, accu(test9$sold_count,testprediction9[,..i],colnames(testprediction9[,..i])))
}



## forcast next day




add_arima(product9,1,7)
mul_arima(product9,1,7)
xreg_mul_arima(product9,1,7, xreg9)
xreg_add_arima(product9,1,7, xreg9)
forecast_lm9(product9,nextday)$forecast
InvBoxCox(forecast_BoxCox9(product9,nextday)$forecast, lambda = lambda)
(forecast_lm9_sqrt(product9,nextday)$forecast)^2






 






```


