---
title: "homework-4/5"
author: "seymacakir"
date: "02 07 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```



```{r}
# install the required packages first
require(jsonlite)
require(httr)
require(data.table)
library(lubridate)
library(data.table)
library(dplyr)
library(ggplot2)
library(knitr)
library(tidyr)
library(tidyverse)
library(scales)
library(ggcorrplot)
library(forecast)
library(urca)
library(zoo)
library(reshape)
library(GGally)
library(PerformanceAnalytics)


get_token <- function(username, password, url_site){
  
  post_body = list(username=username,password=password)
  post_url_string = paste0(url_site,'/token/')
  result = POST(post_url_string, body = post_body)
  
  # error handling (wrong credentials)
  if(result$status_code==400){
    print('Check your credentials')
    return(0)
  }
  else if (result$status_code==201){
    output = content(result)
    token = output$key
  }
  
  return(token)
}

get_data <- function(start_date='2020-03-20', token, url_site){
  
  post_body = list(start_date=start_date,username=username,password=password)
  post_url_string = paste0(url_site,'/dataset/')
  
  header = add_headers(c(Authorization=paste('Token',token,sep=' ')))
  result = GET(post_url_string, header, body = post_body)
  output = content(result)
  data = data.table::rbindlist(output)
  data[,event_date:=as.Date(event_date)]
  data = data[order(product_content_id,event_date)]
  return(data)
}


send_submission <- function(predictions, token, url_site, submit_now=F){
  
  format_check=check_format(predictions)
  if(!format_check){
    return(FALSE)
  }
  
  post_string="list("
  for(i in 1:nrow(predictions)){
    post_string=sprintf("%s'%s'=%s",post_string,predictions$product_content_id[i],predictions$forecast[i])
    if(i<nrow(predictions)){
      post_string=sprintf("%s,",post_string)
    } else {
      post_string=sprintf("%s)",post_string)
    }
  }
  
  submission = eval(parse(text=post_string))
  json_body = jsonlite::toJSON(submission, auto_unbox = TRUE)
  submission=list(submission=json_body)
  
  print(submission)
  # {"31515569":2.4,"32737302":2.4,"32939029":2.4,"4066298":2.4,"48740784":2.4,"6676673":2.4, "7061886":2.4, "73318567":2.4, "85004":2.4} 
  
  if(!submit_now){
    print("You did not submit.")
    return(FALSE)      
  }
  
  
  header = add_headers(c(Authorization=paste('Token',token,sep=' ')))
  post_url_string = paste0(url_site,'/submission/')
  result = POST(post_url_string, header, body=submission)
  
  if (result$status_code==201){
    print("Successfully submitted. Below you can see the details of your submission")
  } else {
    print("Could not submit. Please check the error message below, contact the assistant if needed.")
  }
  
  print(content(result))
  
}

check_format <- function(predictions){
  
  if(is.data.frame(predictions) | is.data.frame(predictions)){
    if(all(c('product_content_id','forecast') %in% names(predictions))){
      if(is.numeric(predictions$forecast)){
        print("Format OK")
        return(TRUE)
      } else {
        print("forecast information is not numeric")
        return(FALSE)                
      }
    } else {
      print("Wrong column names. Please provide 'product_content_id' and 'forecast' columns")
      return(FALSE)
    }
    
  } else {
    print("Wrong format. Please provide data.frame or data.table object")
    return(FALSE)
  }
  
}

# this part is main code
subm_url = 'http://46.101.163.177'

u_name = "Group3"
p_word = "LaQjwxkIGSGhBrRj"
submit_now = TRUE

username = u_name
password = p_word

token = get_token(username=u_name, password=p_word, url=subm_url)
data = get_data(token=token,url=subm_url)

predictions=unique(data[,list(product_content_id)])
predictions[,forecast:= c(224,110,122,494,2,474,22,62,56)]
predictions
#send_submission(predictions, token, url=subm_url, submit_now=T)
```

```{r}
rawdata <- read.csv("C:/Users/seyma/OneDrive/Belgeler/GitHub/spring21-seymacakir/files/project/ProjectRawData.csv", header = TRUE,sep = ",")
rawdata <- as.data.table(rawdata)
colnames <- c( "price","event_date","product_content_id","sold_count" , "visit_count" , "favored_count" , "basket_count","category_sold",     "category_brand_sold", "category_visits"  ,   "ty_visits"  ,  "category_basket",    "category_favored" )
rawdata <- rawdata[,..colnames]
rawdata <- rawdata[!is.na(sold_count)]
rawdata$event_date <- as.Date(rawdata$event_date, format = "%Y-%m-%d")
#rawdata$product_content_id <- as.factor(rawdata$product_content_id)
#data$product_content_id <- as.factor(data$product_content_id)



rawdata <- rbind(rawdata,data) %>% distinct(event_date, product_content_id, .keep_all = TRUE ) %>% arrange(event_date) %>% as.data.table()
 

forecastdata <- tail(rawdata,9) 
forecastdata[, event_date := as.Date(tail(rawdata,9)$event_date + 1)]

rawdata <- rbind(rawdata,forecastdata) %>% distinct(event_date, product_content_id, .keep_all = TRUE ) %>% arrange(event_date) %>% as.data.table()

 # add  month and weekday  component data 

rawdata[,w_day:= wday(event_date)]
rawdata[,mon:= month(event_date)]

forecastdata[,w_day:= wday(event_date)]
forecastdata[,mon:= month(event_date)]


# campaign 

rawdata[, is_campaign := 0]
rawdata[rawdata$event_date >= as.Date("2021-05-07") & rawdata$event_date <= as.Date("2021-05-09"), is_campaign := 1]
rawdata[rawdata$event_date >= as.Date("2020-06-18") & rawdata$event_date <= as.Date("2020-06-20") , is_campaign := 1]
rawdata[rawdata$event_date >= as.Date("2021-06-18") & rawdata$event_date <= as.Date("2021-06-20") , is_campaign := 1]
rawdata[rawdata$event_date >= as.Date("2020-09-08") & rawdata$event_date <= as.Date("2020-09-12") , is_campaign := 1]
rawdata[rawdata$event_date >= as.Date("2021-09-10") & rawdata$event_date <= as.Date("2021-09-12") , is_campaign := 1]
rawdata[rawdata$event_date >= as.Date("2020-11-09") & rawdata$event_date <= as.Date("2020-11-11") , is_campaign := 1]
rawdata[rawdata$event_date >= as.Date("2020-11-25") & rawdata$event_date <= as.Date("2020-11-29") , is_campaign := 1]
rawdata[rawdata$event_date >= as.Date("2021-03-09") & rawdata$event_date <= as.Date("2021-03-12") , is_campaign := 1]
rawdata[rawdata$event_date >= as.Date("2021-04-27") & rawdata$event_date <= as.Date("2021-04-29") , is_campaign := 1]
rawdata[rawdata$event_date >= as.Date("2021-06-09") & rawdata$event_date <= as.Date("2021-06-10") , is_campaign := 1]
rawdata[rawdata$event_date >= as.Date("2020-12-21") & rawdata$event_date <= as.Date("2020-12-24") , is_campaign := 1]





# create data table for each product

product_id <- unique(rawdata$product_content_id)
products <- list()
for ( i in 1:length(product_id)){
products[[i]] <- as.data.table(rawdata[product_content_id == product_content_id[i]])
}


```






```{r}


accu=function(actual,forecast,model){
  model = model
  n=length(actual)
  error=actual-forecast
  mean=mean(actual)
  sd=sd(actual)
  CV=sd/mean
  FBias=sum(error)/sum(actual)
  MAPE=sum(abs(error/actual))/n
  RMSE=sqrt(sum(error^2)/n)
  MAD=sum(abs(error))/n
  MADP=sum(abs(error))/sum(abs(actual))
  WMAPE=MAD/mean
  l=data.frame(model,n,mean,sd,CV,FBias,MAPE,RMSE,MAD,MADP,WMAPE)
  return(l)
}
add_arima=function(data,h,f){
 ts <- ts(data$sold_count,frequency =f )
 add <- decompose(ts, type = "add") 
 fitted <- auto.arima(add$random, seasonal= FALSE)
 seasonal <- add$seasonal[(length(data$sold_count)-f): (length(data$sold_count)-f+h-1)]
 trend <- tail(add$trend[!is.na(add$trend)],1)
 forecastted <- as.numeric(forecast(fitted,h)$mean) + seasonal + trend
 return(forecastted)
}

xreg_add_arima=function(data,h,f, xreg){
 ts <- ts(data$sold_count,frequency =f )
 add <- decompose(ts, type = "add") 
 train_xreg<- xreg[1:length(data$event_date)]
 for_xreg <- xreg[(length(data$event_date))]
 fitted <- auto.arima(add$random, seasonal= FALSE, xreg = train_xreg)
 seasonal <- add$seasonal[(length(data$sold_count)-f): (length(data$sold_count)-f+h-1)]
 trend <- tail(add$trend[!is.na(add$trend)],1)
 forecastted <- as.numeric(forecast(fitted,h,xreg = for_xreg)$mean) + seasonal + trend
 return(forecastted)
}

```

```{r}

i =7
product7 <- products[[7]]




product7[is.na(price)]$price <- mean(product7[!is.na(price)]$price)

product7[,trend := 1:.N]


acf(product7$sold_count)
pacf(product7$sold_count)

product7[ty_visits==1, ty_visits:= mean(ty_visits)]
product7 [, lag1:= shift(sold_count,1)]
product7[is.na(lag1), lag1 := 0]
product7 [, lag2:= shift(sold_count,2)]
product7[is.na(lag2), lag2 := mean(sold_count[1]) ]
product7 [, lag3:= shift(sold_count,3)]
product7[is.na(lag3), lag3 := mean(sold_count[1:2]) ]
product7 [, lag7:= shift(sold_count,7)]
product7[is.na(lag7), lag7 := mean(sold_count[1:6]) ]

product7 [, plag1:= shift(price,1)]
product7[is.na(plag1), plag1 := mean(price) ]


product7[, sqrt:= sqrt(sold_count)]
lambda <- BoxCox.lambda(product7$sold_count)
product7[, BoxCox := BoxCox(sold_count,lambda = lambda)]

test_dates <- tail(product7,15)$event_date
nextday <- tail(product7,1)
train7 <-  product7[!(event_date %in% test_dates)]
test_dates <- test_dates[1:14]
test7 <- product7[event_date %in% test_dates][1:14]

forecast_ahead <- 1

temp <- tail(product7[,c(1,5,6,7,8,9,10,11,12,13)],15)

test7[,c(1,5,6,7,8,9,10,11,12,13)] <- temp[1:14]



my_data <- product7[, 4:13]
chart.Correlation(my_data, pch=19)


xreg7 <- product7[ , c( "price","visit_count",  "basket_count","category_basket" , "ty_visits","is_campaign")]
xreg7 <- as.matrix(xreg7)



add_arima_forecasted <- c(1:length(test_dates))
reg_add_arima_forecasted <- c(1:length(test_dates))

for(i in 1:length(test_dates)){
    current_date=test_dates[i]-forecast_ahead
    past_data=product7[event_date<=current_date]
    forecast_data=product7[event_date==test_dates[i]]
    
    
   add_arima_forecasted[i] <- add_arima(past_data,1,7)
    reg_add_arima_forecasted[i] <- xreg_add_arima(past_data,1,7,xreg7)
}
    
 
 testprediction7 <- data.table("event_date" = test_dates,add_arima_forecasted,reg_add_arima_forecasted)

for(i in 2:length(testprediction7)){
  
  print(accu(test7$sold_count,testprediction7[,..i],colnames(testprediction7[,..i])))
}

ggplot() + geom_line(data = product7[event_date %in% test_dates], aes(x= event_date, y = sold_count)) + 
  geom_line(data = testprediction7,aes( x = event_date,y = add_arima_forecasted, color = "add_arima_forecasted"))+ 
   geom_line(data = testprediction7,aes( x = event_date,y = reg_add_arima_forecasted, color = "reg_add_arima_forecasted"))




forecast_lm_arima=function(data,forecast_data){
    fitted_lm=lm(sqrt~   price  + visit_count  + basket_count + ty_visits  + factor(mon)  + lag1 + lag7  + plag1 + factor(is_campaign) + category_basket, data)
    fitted_arima <- auto.arima(fitted$residuals)
    forecasted=predict(fitted_lm,forecast_data) + forecast(fitted_arima, h = 1)
    return(forecast=as.numeric(forecasted))
}






```
```{r}

i=8

g1 <-ggplot(products[[i]], aes( x = event_date, y = sold_count)) + geom_line() + ggtitle(paste("product",i)) +theme_minimal()  
g2 <-ggplot(products[[i]], aes( y = sold_count, fill= factor(w_day))) + geom_boxplot() + 
  ggtitle(paste("product",i))+ theme_minimal() 
g3 <-ggplot(products[[i]], aes( y = sold_count, fill= factor(mon))) + geom_boxplot()+
      ggtitle(paste("product",i))+ theme_minimal() 
g4 <- ggplot(products[[i]], aes( x = sold_count)) + geom_histogram() + ggtitle(paste("product",i)) + theme_minimal()+
        facet_wrap(~factor(w_day))
g5 <-ggplot(products[[i]], aes( x = sold_count )) + geom_histogram() + theme_minimal()+ ggtitle(paste("product",i))+
      facet_wrap(~factor(mon))


print(g1)
print(g2)
print(g3)
print(g4)
print(g5)
ACF <- acf( products[[i]]$sold_count, plot = FALSE)
plot(ACF, main = paste("ACF OF Product",i))
PACF <- pacf( products[[i]]$sold_count, plot = FALSE)
plot(PACF, main = paste("PACF OF Product",i))
gglagplot(products[[i]]$sold_count, lags = 15)
gglagplot(products[[i]]$sold_count, lags = 30)

my_data <- product7[, 4:13]
chart.Correlation(my_data, pch=19)

daily <- ts(products[[i]]$sold_count, frequency = 7 )
ggsubseriesplot(daily) +
  ylab("daily sales ") +
  ggtitle(" Daily sales")

ggtsdisplay(daily) 

gglagplot(daily)

print("the additive model")
ur.kpss(decompose(daily, type = "add")$random)
print("the multiplicative model")
ur.kpss(decompose(daily, type = "mul")$random)


decomposed_daily <- decompose(daily) 

autoplot(decomposed_daily)

acf(decomposed_daily$random, lag = 14, na.action = na.pass)
pacf(decomposed_daily$random, lag = 14, na.action = na.pass)

fortnight <- ts(products[[i]]$sold_count, frequency = 14 )
ggsubseriesplot(fortnight) +
  ylab("fortnight sales ") +
  ggtitle(" fortnight sales")

ggtsdisplay(fortnight) 

gglagplot(fortnight)

print("the additive model")
ur.kpss(decompose(fortnight, type = "add")$random)
print("the multiplicative model")
ur.kpss(decompose(fortnight, type = "mul")$random)


decomposed_fortnight <- decompose(fortnight) 

autoplot(decomposed_fortnight)

acf(decomposed_fortnight$random, lag = 14, na.action = na.pass)
pacf(decomposed_fortnight$random, lag = 14, na.action = na.pass)






monthly <- ts(products[[i]]$sold_count, frequency = 30 )
ggsubseriesplot(monthly) +
  ylab(" monthly ") +
  ggtitle(" monthly")

ggtsdisplay(monthly) 

gglagplot(monthly)

print("the additive model")
ur.kpss(decompose(monthly, type = "add")$random)
print("the multiplicative model")
ur.kpss(decompose(monthly, type = "mul")$random)


decomposed_monthly <- decompose(monthly) 

autoplot(decomposed_monthly)

acf(decomposed_monthly$random, lag = 14, na.action = na.pass)
pacf(decomposed_monthly$random, lag = 14, na.action = na.pass)



product8 <- products[[8]]




product8[is.na(price)]$price <- mean(product8[(!is.na(price)) & (price>= 0) ]$price)
product8[price<=0]$price <- mean(product8[!is.na(price)]$price)



summary(product8)


product8[,trend := 1:.N]

product8[ty_visits==1, ty_visits:= mean(ty_visits)]
product8 [, lag1:= shift(sold_count,1)]
product8[is.na(lag1), lag1 := 0]
product8 [, lag2:= shift(sold_count,2)]
product8[is.na(lag2), lag2 := mean(sold_count[1]) ]
product8 [, lag5:= shift(sold_count,5)]
product8[is.na(lag5), lag5 := mean(sold_count[1:4]) ]
product8 [, lag7:= shift(sold_count,7)]
product8[is.na(lag7), lag7 := mean(sold_count[1:6]) ]




product8[ , price_lag_4 := shift(price,4)]
product8[ , price_lag_5 := shift(price,5)]
product8[ , price_lag_6 := shift(price,6)]
product8[ , price_lag_1 := shift(price,1)]
product8[is.na(price_lag_4), price_lag_4:= mean(price) ]
product8[is.na(price_lag_5), price_lag_5:= mean(price) ]
product8[is.na(price_lag_6), price_lag_6:= mean(price) ]
product8[is.na(price_lag_1), price_lag_1:= mean(price) ]







product8[, sqrt:= sqrt(sold_count)]
lambda <- BoxCox.lambda(product8$sold_count)
product8[, BoxCox := BoxCox(sold_count,lambda = lambda)]

test_dates <- tail(product8,15)$event_date
nextday <- tail(product8,1)
train8 <-  product8[!(event_date %in% test_dates)]
test_dates <- test_dates[1:14]
test8 <- product8[event_date %in% test_dates][1:14]



forecast_ahead <- 1

temp <- tail(product8[,c(1,5,6,7,8,9,10,11,12,13)],15)

test8[,c(1,5,6,7,8,9,10,11,12,13)] <- temp[1:14]


#my_data <- product8[, 4:13]
#chart.Correlation(my_data, pch=19)


xreg8 <- product8[ , c( "price","visit_count",  "basket_count","category_favored" )]
xreg8 <- as.matrix(xreg8)



for(i in 1:length(test_dates)){
    current_date=test_dates[i]-forecast_ahead
    past_data=product8[event_date<=current_date]
    forecast_data=product8[event_date==test_dates[i]]
    
    
  add_arima_forecasted[i] <- round(add_arima(past_data,1,7),0)
  reg_add_arima_forecasted[i] <- round(xreg_add_arima(past_data,1,7,xreg8),0)
    
}


testprediction8 <- data.table("event_date" = test_dates,add_arima_forecasted,reg_add_arima_forecasted)

for(i in 2:length(testprediction8)){
  
  print(accu(test8$sold_count,testprediction8[,..i],colnames(testprediction8[,..i])))
}

ggplot() + geom_line(data = product8[event_date %in% test_dates], aes(x= event_date, y = sold_count)) + 
  geom_line(data = testprediction8,aes( x = event_date,y = add_arima_forecasted, color = "add_arima_forecasted"))+ 
   geom_line(data = testprediction8,aes( x = event_date,y = reg_add_arima_forecasted, color = "reg_add_arima_forecasted"))
```


```{r}
i=9

g1 <-ggplot(products[[i]], aes( x = event_date, y = sold_count)) + geom_line() + ggtitle(paste("product",i)) +theme_minimal()  
g2 <-ggplot(products[[i]], aes( y = sold_count, fill= factor(w_day))) + geom_boxplot() + 
  ggtitle(paste("product",i))+ theme_minimal() 
g3 <-ggplot(products[[i]], aes( y = sold_count, fill= factor(mon))) + geom_boxplot()+
      ggtitle(paste("product",i))+ theme_minimal() 
g4 <- ggplot(products[[i]], aes( x = sold_count)) + geom_histogram() + ggtitle(paste("product",i)) + theme_minimal()+
        facet_wrap(~factor(w_day))
g5 <-ggplot(products[[i]], aes( x = sold_count )) + geom_histogram() + theme_minimal()+ ggtitle(paste("product",i))+
      facet_wrap(~factor(mon))


print(g1)
print(g2)
print(g3)
print(g4)
print(g5)
ACF <- acf( products[[i]]$sold_count, plot = FALSE)
plot(ACF, main = paste("ACF OF Product",i))
PACF <- pacf( products[[i]]$sold_count, plot = FALSE)
plot(PACF, main = paste("PACF OF Product",i))
gglagplot(products[[i]]$sold_count, lags = 15)
gglagplot(products[[i]]$sold_count, lags = 30)


daily <- ts(products[[i]]$sold_count, frequency = 7 )
ggsubseriesplot(daily) +
  ylab("daily sales ") +
  ggtitle(" Daily sales")

ggtsdisplay(daily) 

gglagplot(daily)

print("the additive model")
ur.kpss(decompose(daily, type = "add")$random)
print("the multiplicative model")
ur.kpss(decompose(daily, type = "mul")$random)


decomposed_daily <- decompose(daily) 

autoplot(decomposed_daily)

acf(decomposed_daily$random, lag = 14, na.action = na.pass)
pacf(decomposed_daily$random, lag = 14, na.action = na.pass)

fortnight <- ts(products[[i]]$sold_count, frequency = 14 )
ggsubseriesplot(fortnight) +
  ylab("fortnight sales ") +
  ggtitle(" fortnight sales")

ggtsdisplay(fortnight) 

gglagplot(fortnight)

print("the additive model")
ur.kpss(decompose(fortnight, type = "add")$random)
print("the multiplicative model")
ur.kpss(decompose(fortnight, type = "mul")$random)


decomposed_fortnight <- decompose(fortnight) 

autoplot(decomposed_fortnight)

acf(decomposed_fortnight$random, lag = 14, na.action = na.pass)
pacf(decomposed_fortnight$random, lag = 14, na.action = na.pass)






monthly <- ts(products[[i]]$sold_count, frequency = 30 )
ggsubseriesplot(monthly) +
  ylab(" monthly ") +
  ggtitle(" monthly")

ggtsdisplay(monthly) 

gglagplot(monthly)

print("the additive model")
ur.kpss(decompose(monthly, type = "add")$random)
print("the multiplicative model")
ur.kpss(decompose(monthly, type = "mul")$random)


decomposed_monthly <- decompose(monthly) 

autoplot(decomposed_monthly)

acf(decomposed_monthly$random, lag = 14, na.action = na.pass)
pacf(decomposed_monthly$random, lag = 14, na.action = na.pass)




product9 <- products[[9]]


summary(product9)



product9[is.na(price)]$price <- mean(product9[(!is.na(price)) & (price>= 0) ]$price)
product9[price<=0]$price <- mean(product9[!is.na(price)]$price)



product9[,trend := 1:.N]

product9[ty_visits==1, ty_visits:= mean(ty_visits)]
product9 [, lag1:= shift(sold_count,1)]
product9[is.na(lag1), lag1 := 0]
product9 [, lag2:= shift(sold_count,2)]
product9[is.na(lag2), lag2 := mean(sold_count[1]) ]
product9 [, lag3:= shift(sold_count,3)]
product9[is.na(lag3), lag3 := mean(sold_count[1:2]) ]
product9 [, lag7:= shift(sold_count,7)]
product9[is.na(lag7), lag7 := mean(sold_count[1:6]) ]





product9[, sqrt:= sqrt(sold_count)]
lambda <- BoxCox.lambda(product9$sold_count)
product9[, BoxCox := BoxCox(sold_count,lambda = lambda)]

test_dates <- tail(product9,15)$event_date
nextday <- tail(product9,1)
train9 <-  product9[!(event_date %in% test_dates)]
test_dates <- test_dates[1:14]
test9 <- product9[event_date %in% test_dates][1:14]



forecast_ahead <- 1



temp <- tail(product9[,c(1,5,6,7,8,9,10,11,12,13)],15)

test9[,c(1,5,6,7,8,9,10,11,12,13)] <- temp[1:14]


xreg9 <- product9[ , c( "price","category_sold",  "basket_count","category_favored" )]
xreg9 <- as.matrix(xreg9)

 add_arima_forecasted <- c(1:length(test_dates))
 reg_add_arima_forecasted <- c(1:length(test_dates))

for(i in 1:length(test_dates)){
    current_date=test_dates[i]-forecast_ahead
    past_data=product9[event_date<=current_date]
    forecast_data=product9[event_date==test_dates[i]]
    
    
    add_arima_forecasted[i] <- add_arima(past_data,1,7)
    reg_add_arima_forecasted[i] <- xreg_add_arima(past_data,1,7,xreg9)

}

 testprediction9 <- data.table("event_date" = test_dates,add_arima_forecasted,reg_add_arima_forecasted)

for(i in 2:length(testprediction9)){
  
  print(accu(test9$sold_count,testprediction9[,..i],colnames(testprediction9[,..i])))
}

ggplot() + geom_line(data = product9[event_date %in% test_dates], aes(x= event_date, y = sold_count)) + 
  geom_line(data = testprediction9,aes( x = event_date,y = add_arima_forecasted, color = "add_arima_forecasted"))+ 
   geom_line(data = testprediction9,aes( x = event_date,y = reg_add_arima_forecasted, color = "reg_add_arima_forecasted"))



```

